INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(1, 2, 2, 3);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(2, 2, 4, 5);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(3, 2, 6, 7);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(4, 2, 8, 9);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(5, 1, 1, 24);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(6, 2, 10, 11);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(7, 2, 12, 19);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(8, 3, 15, 16);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(9, 3, 17, 18);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(10, 2, 20, 21);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(11, 3, 13, 14);
INSERT OR IGNORE INTO node_tree(idNode, level, iLeft, iRight) VALUES(12, 2, 22, 23);
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(1, 'english', 'Marketing');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(1, 'italian', 'Marketing');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(2, 'english', 'Helpdesk');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(2, 'italian', 'Supporto tecnico');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(3, 'english', 'Managers');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(3, 'italian', 'Managers');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(4, 'english', 'Customer Account');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(4, 'italian', 'Assistenza Cliente');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(5, 'english', 'Docebo');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(5, 'italian', 'Docebo');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(6, 'english', 'Accounting');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(6, 'italian', 'Amministrazione');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(7, 'english', 'Sales');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(7, 'italian', 'Supporto Vendite');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(8, 'english', 'Italy');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(8, 'italian', 'Italia');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(9, 'english', 'Europe');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(9, 'italian', 'Europa');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(10, 'english', 'Developers');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(10, 'italian', 'Sviluppatori');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(11, 'english', 'North America');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(11, 'italian', 'Nord America');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(12, 'english', 'Quality Assurance');
INSERT OR IGNORE INTO node_tree_names(idNode, language, nodeName) VALUES(12, 'italian', 'Controllo Qualità')